plugins:
  - import
  - jest
  - prettier
  # - babel

parser: babel-eslint

extends:
  - airbnb-base
  - plugin:jest/recommended
  - plugin:prettier/recommended

env:
  node: true
  jest: true

rules:
  no-console: 'off'
